# Индивидуальное задание

Вариант 12: Осуществить циклический сдвиг элементов квадратной матрицы размерности M x N вправо на к элементов таким образом: элементы 1-й строки сдвигаются в последний столбец сверху вниз, из него - в последнюю строку справа налево, из нее - в первый столбец снизу вверх, из него - в первую строку; для остальных элементов - аналогично.

In [48]:
import numpy as np

In [38]:
# создаём матрицу 3 х 3
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# количество сдвигов
k = 1
count = 0
while count < k:
    # Сохраняем первую строку матрицы
    first_row = matrix[0, :].copy()
    # Сдвигаем элементы первой строки в последний столбец сверху вниз
    matrix[:-1, -1] = matrix[1:, -1]
    # Сдвигаем элементы последнего столбца в последнюю строку справа налево
    matrix[-1, 1:] = matrix[-1, :-1]
    # Сдвигаем элементы последней строки в первый столбец снизу вверх
    matrix[1:, 0] = matrix[:-1, 0]
    # Сдвигаем элементы первого столбца в первую строку слева направо
    matrix[0, :-1] = first_row[1:]
    count += 1
# вывод получившейся матрицы 
print(matrix)

[[2 3 6]
 [1 5 9]
 [4 7 8]]
